### PR TITLE
Valid time interval to NSDateComponentsFormatter

### LINKED ISSUE #127: SRGTimeSlider throws an exception
### Issue type

Crash

### Description of the problem

In some cases, an on demand content seems to not have yet a maximum value.
`SRGTimeSliderFormatter(NSTimeInterval seconds)`  method throws an exception.

```
SRGTimeSliderFormatter
once.h
SIGABRT: Invalid parameter not satisfying: isfinite(timeInterval) && !isnan(timeInterval)

CoreFoundation   __exceptionPreprocess
libobjc.A.dylib  objc_exception_throw
Foundation       -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:]
Foundation       -[NSDateComponentsFormatter stringFromTimeInterval:]
Play RSI         SRGTimeSliderFormatter once.h:0
Play RSI         -[SRGTimeSlider updateTimeRangeLabelsWithTime:] SRGTimeSlider~ios.m:356
Play RSI         -[SRGTimeSlider updateDisplayWithTime:] SRGTimeSlider~ios.m:265
Play RSI         -[SRGTimeSlider setMediaPlayerController:] SRGTimeSlider~ios.m:128
Play RSI         -[SRGPeriodicTimeObserver startObservers] SRGPeriodicTimeObserver.m:115
Play RSI         -[SRGPeriodicTimeObserver startObservers] SRGPeriodicTimeObserver.m:131
Play RSI         -[_MAKVONotificationHelper observeValueForKeyPath:ofObject:change:context:] MAKVONotificationCenter.m:146
Foundation       -[NSKeyValueObservance observeValueForKeyPath:ofObject:change:context:]
```

### Environment information

* Library version: [7.1.0](https://github.com/SRGSSR/srgmediaplayer-apple/tree/7.1.0)
* iOS / tvOS version: Any iOS? 16.5, 16.5.1, etc
* Device: Any iOS devices

### Reproducibility

Difficult to reproduce

### Code sample

```
[SRGTimeSlider updateTimeRangeLabelsWithTime:] SRGTimeSlider~ios.m:356
```

Replace `interval` with `0.0/0.0` and play a VoD or an AoD with custom player.

### Crash logs from Play SRG Apple apps:

Play RSI 3.7.1: https://appcenter.ms/orgs/RTS-Organization/apps/Play-RSI-1/crashes/errors/1306846231u/overview
Play RTS 3.7.1: https://appcenter.ms/orgs/RTS-Organization/apps/Play-RTS-1/crashes/errors/1306846231u/overview
Play SRF 3.7.1: https://appcenter.ms/orgs/RTS-Organization/apps/Play-SRF-1/crashes/errors/1306846231u/overview

### PR DESCRIPTION
**Pull request by pyby**
### Motivation and Context

Documented in issue #127.

### Description

- Check `NSTimeInterval` is valid to `NSDateComponentsFormatter` and `SRGTimeSliderFormatter(NSTimeInterval seconds)` method.
- Add public macro, so that `SRGLetterbox` library could use it also for additional player UI controls. https://github.com/SRGSSR/srgletterbox-apple/pull/303

### Checklist

- [x] The branch should be rebased onto the `develop` branch for whole tests with last commits.
- [x] The documentation has been updated (if relevant).
- [x] Issues are linked to the PR, if any.

### CODE REVIEW

File: Sources/SRGMediaPlayer/SRGTimeSlider~ios.m [hunk 1]
```diff
@@ -23,6 +24,8 @@
 static NSString *SRGTimeSliderFormatter(NSTimeInterval seconds)
 {
     NSCAssert(seconds >= 0, @"A non-negative number of seconds is expected");
+    NSCAssert(!isnan(seconds), @"A number of seconds is expected");
+    NSCAssert(!isinf(seconds), @"A non-infinite number of seconds is expected");
```
Comment (defagos) [inline Sources/SRGMediaPlayer/SRGTimeSlider~ios.m]: Since you are now addressing these exceptional conditions directly I would suggest we remove assertions entirely. Assertions should make it possible to identify obvious programming errors but here we obviously needed to be more resilient to cases that can actually happen in practice.

**Review by defagos — APPROVED** [review]

File: Sources/SRGMediaPlayer/SRGTimeSlider~ios.m (hunk 1 above)
Comment (pyby) [reply Sources/SRGMediaPlayer/SRGTimeSlider~ios.m]: Good point. Did it.
